# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e8378ea27892fb70f2ae944512457886350e390aa8f1eb0a8d7ff3e30825394a66bbe04aeeeda9713abdc033c2189328f91774b667f27ffd05d956e6980031f

test:
  secret_key_base: ab8cd2d62d9f22d6d7479e367b71ae39f90701572b363a6eb732e0732cb17ebf518db0b86afaa91f622adfa371cb0b4132c7bf5c14750af10073766b8341b3c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 6e8378ea27892fb70f2ae944512457886350e390aa8f1eb0a8d7ff3e30825394a66bbe04aeeeda9713abdc033c2189328f91774b667f27ffd05d956e6980031f
